// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.4

package user

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheQqForumUserIdPrefix       = "cache:qqForum:user:id:"
	cacheQqForumUserEmailPrefix    = "cache:qqForum:user:email:"
	cacheQqForumUserUsernamePrefix = "cache:qqForum:user:username:"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*User, error)
		FindOneByEmail(ctx context.Context, email string) (*User, error)
		FindOneByUsername(ctx context.Context, username string) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserModel struct {
		sqlc.CachedConn
		table string
	}

	User struct {
		Id        int64        `db:"id"`        // user id
		Email     string       `db:"email"`     // email
		Password  string       `db:"password"`  // password
		Username  string       `db:"username"`  // username
		Avatar    string       `db:"avatar"`    // avatar
		Signature string       `db:"signature"` // signature
		Birthday  sql.NullTime `db:"birthday"`  // birthday
		Role      string       `db:"role"`      // role
		Status    string       `db:"status"`    // status
		IsDeleted int64        `db:"is_deleted"`
		CreatedAt time.Time    `db:"created_at"`
		UpdatedAt time.Time    `db:"updated_at"`
	}
)

func newUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserModel {
	return &defaultUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user`",
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	qqForumUserEmailKey := fmt.Sprintf("%s%v", cacheQqForumUserEmailPrefix, data.Email)
	qqForumUserIdKey := fmt.Sprintf("%s%v", cacheQqForumUserIdPrefix, id)
	qqForumUserUsernameKey := fmt.Sprintf("%s%v", cacheQqForumUserUsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, qqForumUserEmailKey, qqForumUserIdKey, qqForumUserUsernameKey)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id int64) (*User, error) {
	qqForumUserIdKey := fmt.Sprintf("%s%v", cacheQqForumUserIdPrefix, id)
	var resp User
	err := m.QueryRowCtx(ctx, &resp, qqForumUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByEmail(ctx context.Context, email string) (*User, error) {
	qqForumUserEmailKey := fmt.Sprintf("%s%v", cacheQqForumUserEmailPrefix, email)
	var resp User
	err := m.QueryRowIndexCtx(ctx, &resp, qqForumUserEmailKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `email` = ? limit 1", userRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, email); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByUsername(ctx context.Context, username string) (*User, error) {
	qqForumUserUsernameKey := fmt.Sprintf("%s%v", cacheQqForumUserUsernamePrefix, username)
	var resp User
	err := m.QueryRowIndexCtx(ctx, &resp, qqForumUserUsernameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", userRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, username); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	qqForumUserEmailKey := fmt.Sprintf("%s%v", cacheQqForumUserEmailPrefix, data.Email)
	qqForumUserIdKey := fmt.Sprintf("%s%v", cacheQqForumUserIdPrefix, data.Id)
	qqForumUserUsernameKey := fmt.Sprintf("%s%v", cacheQqForumUserUsernamePrefix, data.Username)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Email, data.Password, data.Username, data.Avatar, data.Signature, data.Birthday, data.Role, data.Status, data.IsDeleted)
	}, qqForumUserEmailKey, qqForumUserIdKey, qqForumUserUsernameKey)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, newData *User) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	qqForumUserEmailKey := fmt.Sprintf("%s%v", cacheQqForumUserEmailPrefix, data.Email)
	qqForumUserIdKey := fmt.Sprintf("%s%v", cacheQqForumUserIdPrefix, data.Id)
	qqForumUserUsernameKey := fmt.Sprintf("%s%v", cacheQqForumUserUsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Email, newData.Password, newData.Username, newData.Avatar, newData.Signature, newData.Birthday, newData.Role, newData.Status, newData.IsDeleted, newData.Id)
	}, qqForumUserEmailKey, qqForumUserIdKey, qqForumUserUsernameKey)
	return err
}

func (m *defaultUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheQqForumUserIdPrefix, primary)
}

func (m *defaultUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
