// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type BaseResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type DeleteReq struct {
	UserId int64 `json:"user_id"`
}

type DeleteResp struct {
	BaseResp
}

type GetInfoReq struct {
	UserId int64 `json:"user_id"`
}

type GetInfoResp struct {
	BaseResp
	UserInfo UserInfo `json:"user_info"`
}

type LoginReq struct {
	Email    string `json:"email,optional"`
	Username string `json:"username,optional"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseResp
	Token  string `json:"token"`
	UserId int64  `json:"user_id"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	BaseResp
	UserId int64 `json:"user_id"`
}

type UpdateReq struct {
	UserId   int64    `json:"user_id"`
	UserInfo UserInfo `json:"user_info"`
}

type UpdateResp struct {
	BaseResp
	UserInfo UserInfo `json:"user_info"`
}

type UserInfo struct {
	Id             int64
	Email          string
	Password       string
	Username       string
	Avatar         string
	Signature      string
	BirthdayStr    string
	Role           string
	Status         string
	IsDeleted      int64
	CreatedTimeStr string
	UpdatedTimeStr string
}