// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AdminInfo struct {
	Id          int64  `json:"id"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	Username    string `json:"username"`
	Phone       string `json:"phone"`
	Status      int64  `json:"status"`
	IsDeleted   int64  `json:"is_deleted"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

type BaseResp struct {
	Code    int64  `json:"code"`    // 响应码
	Message string `json:"message"` // 响应信息
}

type CategoryInfo struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	SortOrder   int64  `json:"sort_order"`
	IsActive    int64  `json:"is_active"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

type CommentInfo struct {
	Id          int64  `json:"id"`
	Content     string `json:"content"`
	UserId      int64  `json:"user_id"`
	PostId      int64  `json:"post_id"`
	ParentId    int64  `json:"parent_id"`
	LikeCount   int64  `json:"like_count"`
	Status      string `json:"status"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

type CreateAdminReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
	Phone    string `json:"phone"`
}

type CreateAdminResp struct {
	BaseResp
	Admin AdminInfo `json:"admin"`
}

type CreateCategoryReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	SortOrder   int64  `json:"sort_order"`
}

type CreateCategoryResp struct {
	BaseResp
	CategoryId int64 `json:"category_id"`
}

type CreateCommentReq struct {
	Content  string `json:"content"`
	UserId   int64  `json:"user_id"`
	PostId   int64  `json:"post_id"`
	ParentId int64  `json:"parent_id"`
}

type CreateCommentResp struct {
	BaseResp
	CommentId int64 `json:"comment_id"`
}

type CreatePostReq struct {
	UserId     int64  `json:"user_id"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	CategoryId int64  `json:"category_id,optional"`
}

type CreatePostResp struct {
	BaseResp
	PostId int64 `json:"post_id"`
}

type CreateUserLikeReq struct {
	UserId     int64  `json:"user_id"`
	TargetType string `json:"target_type"`
	TargetId   int64  `json:"target_id"`
}

type CreateUserLikeResp struct {
	BaseResp
	UserLikeId int64 `json:"user_like_id"`
}

type DeleteAdminReq struct {
	Id int64 `json:"id"`
}

type DeleteAdminResp struct {
	BaseResp
}

type DeleteCategoryReq struct {
	Id int64 `json:"id"`
}

type DeleteCategoryResp struct {
	BaseResp
	DeleteType string `json:"delete_type"`
}

type DeleteCommentReq struct {
	Id int64 `json:"id"`
}

type DeleteCommentResp struct {
	BaseResp
}

type DeletePostReq struct {
	Id     int64 `json:"id"`
	UserId int64 `json:"user_id"`
}

type DeletePostResp struct {
	BaseResp
	DeleteType string `json:"delete_type"`
}

type DeleteUserLikeReq struct {
	UserId     int64  `json:"user_id"`
	TargetType string `json:"target_type"`
	TargetId   int64  `json:"target_id"`
}

type DeleteUserLikeResp struct {
	BaseResp
}

type GetAdminReq struct {
	Id int64 `form:"id"`
}

type GetAdminResp struct {
	BaseResp
	Admin AdminInfo `json:"admin"`
}

type GetCategoryReq struct {
	Id int64 `form:"id"`
}

type GetCategoryResp struct {
	BaseResp
	CategoryInfo CategoryInfo `json:"category_info"`
}

type GetCommentReq struct {
	Id int64 `form:"id"`
}

type GetCommentResp struct {
	BaseResp
	Comment CommentInfo `json:"comment"`
}

type GetPostReq struct {
	Id int64 `form:"id"`
}

type GetPostResp struct {
	BaseResp
	Post PostInfo `json:"post"`
}

type GetTargetLikesCountReq struct {
	TargetType string `form:"target_type"`
	TargetId   int64  `form:"target_id"`
}

type GetTargetLikesCountResp struct {
	BaseResp
	LikesCount int64 `json:"likes_count"`
}

type GetUserLikesCountReq struct {
	UserId int64 `form:"user_id"`
}

type GetUserLikesCountResp struct {
	BaseResp
	LikesCount int64 `json:"likes_count"`
}

type GetUserReq struct {
	UserId int64 `form:"user_id"`
}

type GetUserResp struct {
	BaseResp
	UserInfo UserInfo `json:"user_info"`
}

type ListCategoryReq struct {
	PaginationReq
}

type ListCategoryResp struct {
	BaseResp
	CategoryList []CategoryInfo `json:"category_list"`
	Total        int64          `json:"total"`
	TotalPages   int64          `json:"total_pages"`
	CurrentPage  int64          `json:"current_page"`
	HasNextPage  bool           `json:"has_next_page"`
	HasPrevPage  bool           `json:"has_prev_page"`
}

type ListCommentReq struct {
	LastIndex int64 `form:"last_index"`
	PageSize  int64 `form:"page_size"`
	PostId    int64 `form:"post_id"`
}

type ListCommentResp struct {
	BaseResp
	Comments  []CommentInfo `json:"comments"`
	LastIndex int64         `json:"last_id"`
}

type ListPostReq struct {
	CategoryId int64  `form:"category_id,optional"`
	LastIndex  int64  `form:"last_index"`
	PageSize   int64  `form:"page_size"`
	OrderBy    string `form:"order_by"`
	OrderType  string `form:"order_type"`
}

type ListPostResp struct {
	BaseResp
	Posts   []PostInfo `json:"posts"`
	HasMore bool       `json:"has_more"`
	LastId  int64      `json:"last_id"`
}

type ListUserLikesReq struct {
	UserId int64 `form:"user_id"`
}

type ListUserLikesResp struct {
	BaseResp
	UserLikes []UserLikeInfo `json:"user_likes"`
}

type LoginAdminReq struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginAdminResp struct {
	BaseResp
	Admin        AdminInfo `json:"admin"`
	Token        string    `json:"token"`
	Expire       int64     `json:"expire"`
	RefreshToken string    `json:"refresh_token"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseResp
	Token        string `json:"token"`
	Expire       int64  `json:"expire"`
	RefreshToken string `json:"refresh_token"`
	UserId       int64  `json:"user_id"`
}

type PaginationReq struct {
	Page     int64 `form:"page,optional"`      // 页码，可选，默认1
	PageSize int64 `form:"page_size,optional"` // 每页大小，可选，默认10
}

type PaginationResp struct {
	BaseResp
	Total    int64 `json:"total"`     // 总记录数
	Page     int64 `json:"page"`      // 当前页码
	PageSize int64 `json:"page_size"` // 每页大小
}

type PostInfo struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	Content     string `json:"content"`
	UserId      int64  `json:"user_id"`
	CategoryId  int64  `json:"category_id"`
	Status      string `json:"status"`
	IsTop       int64  `json:"is_top"`
	IsHot       int64  `json:"is_hot"`
	CreatedTime int64  `json:"created_time"`
	UpdatedTime int64  `json:"updated_time"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
}

type RegisterResp struct {
	BaseResp
	UserId int64 `json:"user_id"`
}

type RestorePostReq struct {
	Id int64 `json:"id"`
}

type RestorePostResp struct {
	BaseResp
	PostId int64 `json:"post_id"`
}

type UpdateAdminReq struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
	Phone    string `json:"phone"`
}

type UpdateAdminResp struct {
	BaseResp
	Id int64 `json:"id"`
}

type UpdateCategoryReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
	SortOrder   int64  `json:"sort_order,optional"`
	IsActive    int64  `json:"is_active,optional"`
}

type UpdateCategoryResp struct {
	BaseResp
	CategoryInfo CategoryInfo `json:"category_info"`
}

type UpdateCommentReq struct {
	Id      int64  `json:"id"`
	Content string `json:"content"`
}

type UpdateCommentResp struct {
	BaseResp
}

type UpdatePostReq struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"user_id"`
	Title      string `json:"title,optional"`
	Content    string `json:"content,optional"`
	CategoryId int64  `json:"category_id,optional"`
	Status     int64  `json:"status,optional"`
}

type UpdatePostResp struct {
	BaseResp
	PostId int64 `json:"post_id"`
}

type UpdateUserReq struct {
	UserId   int64  `form:"user_id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
}

type UpdateUserResp struct {
	BaseResp
	UserId int64 `json:"user_id"`
}

type UserInfo struct {
	Id            int64  `json:"id"`
	Email         string `json:"email"`
	Username      string `json:"username"`
	Avatar        string `json:"avatar"`
	Signature     string `json:"signature"`
	Birthday      string `json:"birthday"`
	Phone         string `json:"phone"`
	Status        int64  `json:"status"`
	IsDeleted     int64  `json:"is_deleted"`
	LastLoginTime int64  `json:"last_login_time"`
	CreatedTime   int64  `json:"created_time"`
	UpdatedTime   int64  `json:"updated_time"`
}

type UserLikeInfo struct {
	Id         int64  `json:"id"`
	UserId     int64  `json:"user_id"`
	TargetType string `json:"target_type"`
	TargetId   int64  `json:"target_id"`
	CreatedAt  int64  `json:"created_at"`
}
