// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type BaseResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseResp
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
	Token    string `json:"token"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	BaseResp
	UserId int64 `json:"user_id"`
}
